name: generate snake animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/snake.yml'

concurrency:
  group: snake
  cancel-in-progress: true

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: generate snake with holy paladin palette
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake.svg?color_snake=%23facc15&color_dots=%230b1026,%231e293b,%231d4ed8,%23bfdbfe,%23fef3c7
            dist/snake-light.svg?color_snake=%231d4ed8&color_dots=%23fefce8,%23bfdbfe,%2360a5fa,%23facc15,%230b1026

      - name: push to output branch
        uses: crazy-max/ghaction-github-pages@v5
        with:
          target_branch: output
          build_dir: dist
          keep_history: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
